name: flutter_animator
description: Create animations with less code in a chaining manner. This package allows you to combine and chain multiple animations based on percentages of the duration.
version: 3.1.2
homepage: https://github.com/sharp3dges/animator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
